### PR TITLE
add a web demo for Yi-VL model

### PR DESCRIPTION
**Pull request by Yimi81**
Solve problem #338. @findmyway

### CODE REVIEW

**Comment by Yimi81** [comment]
vl_web_demo

**Comment by choyakawa** [comment]
Is multiple image input applicable?

**Comment by Yimi81** [comment]
@choyakawa sry, no

**Review by findmyway — APPROVED** [review]
LGTM

**Comment by newbietk** [comment]
我进行gradio界面的推理，遇到这个错误，请问知道是什么情况吗？
    return jsonable_encoder(
  File "/data/anaconda3/envs/yi/lib/python3.9/site-packages/fastapi/encoders.py", line 287, in jsonable_encoder
    encoded_value = jsonable_encoder(
  File "/data/anaconda3/envs/yi/lib/python3.9/site-packages/fastapi/encoders.py", line 331, in jsonable_encoder
    return jsonable_encoder(
  File "/data/anaconda3/envs/yi/lib/python3.9/site-packages/fastapi/encoders.py", line 287, in jsonable_encoder
    encoded_value = jsonable_encoder(
  File "/data/anaconda3/envs/yi/lib/python3.9/site-packages/fastapi/encoders.py", line 331, in jsonable_encoder
    return jsonable_encoder(
  File "/data/anaconda3/envs/yi/lib/python3.9/site-packages/fastapi/encoders.py", line 287, in jsonable_encoder
    encoded_value = jsonable_encoder(
  File "/data/anaconda3/envs/yi/lib/python3.9/site-packages/fastapi/encoders.py", line 331, in jsonable_encoder
    return jsonable_encoder(
  File "/data/anaconda3/envs/yi/lib/python3.9/site-packages/fastapi/encoders.py", line 287, in jsonable_encoder
    encoded_value = jsonable_encoder(
  File "/data/anaconda3/envs/yi/lib/python3.9/site-packages/fastapi/encoders.py", line 331, in jsonable_encoder
    return jsonable_encoder(
  File "/data/anaconda3/envs/yi/lib/python3.9/site-packages/fastapi/encoders.py", line 287, in jsonable_encoder
    encoded_value = jsonable_encoder(
  File "/data/anaconda3/envs/yi/lib/python3.9/site-packages/fastapi/encoders.py", line 331, in jsonable_encoder
    return jsonable_encoder(
  File "/data/anaconda3/envs/yi/lib/python3.9/site-packages/fastapi/encoders.py", line 287, in jsonable_encoder
    encoded_value = jsonable_encoder(
  File "/data/anaconda3/envs/yi/lib/python3.9/site-packages/fastapi/encoders.py", line 318, in jsonable_encoder
    if isinstance(obj, classes_tuple):
  File "/data/anaconda3/envs/yi/lib/python3.9/abc.py", line 119, in __instancecheck__
    return _abc_instancecheck(cls, instance)
RecursionError: maximum recursion depth exceeded in comparison

**Comment by Yimi81** [comment]
@newbietk 请确保环境没问题，你可以创建一个新的虚拟环境进行测试：
```
conda create -n yi-vl python=3.10 -y
cd VL
pip install -r requirements.txt
python web_demo.py --model-path path-to-yi-vl-model
```

**Pull request merged**
